### PR TITLE
Set ip if configured, otherwise just bring up link

### PR DESCRIPTION
**Pull request by botto**
This PR makes a change to how we deal with ip addresses. Instead of assuming the IP is set in the config we make an explicit check, this means we support just bringing up interfaces and not configuring their IP address.

I can see advantages of doing this if you expect and external system to deal with IP config (i.e. NetworkManager), but it does go a bit against the dsnet idea of simplicity

### CODE REVIEW

**Comment by botto** [comment]
If we merge this then we can drop #35

**Comment by naggie** [comment]
Wow, massive oversight on my part. Thanks!

**Comment by naggie** [comment]
I think this is a good approach as we require either the IPv4 or IPv6 to be set, or both earlier on.

**Comment by naggie** [comment]
Actually I think this is inconsistent with some other commands that expect at least one of IP/IP6 to be set. I think we should check that at least one exists -- using dsnet without IP management seems like an unneeded feature or scope creep. Do you have a use case beyond networkmanager speculation?

**Comment by botto** [comment]
No, I 

> 
> 
> Actually I think this is inconsistent with some other commands that expect at least one of IP/IP6 to be set. I think we should check that at least one exists -- using dsnet without IP management seems like an unneeded feature or scope creep. Do you have a use case beyond networkmanager speculation?

Maybe DHCP server of some kind, but honestly I'm more inclined to say that dsnet always sets an ip address of some kind, at least until we maybe support some external integration that does that instead
I'll raise a PR soon that does an XOR check

**Comment by naggie** [comment]
Great thanks 👍

**Pull request merged**
