### PR TITLE
Add a NixOS peer config template / generator.

### PR DESCRIPTION
**Pull request by axelsimon**
First attempt at Go, hope all is good.

This will generate a config that should ready to copy and paste into a Nixos `configuration.nix`.
Tests welcome.

### CODE REVIEW

**Comment by naggie** [comment]
Cool, thanks! I recently changed the way config files determine the server peer `Endpoint` though -- moved the logic out of the templates as there is now a third possible option which has precedence, `ExternalHost`. Please could you update the PR to be consistent with the other 2 configs. 
 
Otherwise looks good to me. I assume you've tested that it works.

**Comment by axelsimon** [comment]
Alright, let me look into that.
Yes, i've been testing it and checking the copy-paste really produces something that just works for Nix. Force-pushed a few commits to get to that point ;)

**Comment by axelsimon** [comment]
@naggie Should be good, now. Let me know if it looks good to you :)

**Comment by naggie** [comment]
LGTM -- much appreciated. Thank you!

**Comment by naggie** [comment]
I made a new release, v0.5. 2 in one day!

**Pull request merged**
