### PR TITLE
Error cascade

### PR DESCRIPTION
**Pull request by xxxserxxx**
This version (which can be merged on top of, or instead of, report_errors) replaces `ExitFail()` in the top-level functions, such that errors are passed up to the main function and reported there. Long-term, `ExitFail()` would ideally be removed entirely; by exiting deep in the stack, it prevents calling functions the opportunity to handle and clean up after errors. However, this PR focuses on having consistent behavior in all of the top-level commands by using `RunE()` wherever there can be failures.

### CODE REVIEW

**Comment by xxxserxxx** [comment]
All of these PRs are based on different branches, and they often conflict. If you're going to pull any of them, I recomend pulling issue-69 first, then letting me know which others you do (or don't) want to merge, and letting me resolve the conflicts.

**Comment by naggie** [comment]
Retest this please, Cydarbot!

**Comment by naggie** [comment]
Thanks @xxxserxxx -- I will get the user-keys-master branch merged first I think. A useful change and helps @botto 's plight of separating the cli into a lib. @botto please take a look too.

**Comment by xxxserxxx** [comment]
Rebased naggie/master onto this so it's a clean merge again.

**Comment by naggie** [comment]
@xxxserxxx would you mind resolving the build issue here pls? Feel free to revert my bad merge.

**Comment by xxxserxxx** [comment]
> @xxxserxxx would you mind resolving the build issue here pls? Feel free to revert my bad merge.

Yah, no problem.

**Comment by xxxserxxx** [comment]
Man, I hate git.

I created a new branch, `error_cascade_clean`, that I'll open a new PR for.

**Pull request closed without merging**
