### PR TITLE
Split out dsnet in to lib and cli

### PR DESCRIPTION
**Pull request by botto**
This PR suggest to split out the lib and cli so it's easier for other implementations  to use dsnet as a lib and not worry about cli features causing unexpected exits.

For now this will be a draft to get some initial feedback but also while I work on converting the other commands

### CODE REVIEW

**Comment by naggie** [comment]
Thoughts:

* Util and config probably don't belong in cli
* Please remove vendored changes from the PR

Generally a good idea, dsnet CLI using dsnet as a lib means we're unlikely to make bad choices or side affects that impact other applications.

**Review by naggie — APPROVED** [review]

**Comment by botto** [comment]
Hi @naggie 
Sorry for the long delay on this and the size the PR has grown to, I've done some more work on this since you last checked:
- Separated vendor change in to own pr #62 
- Moved add to new cli
- Moved init to new cli
- Moved regenerate to new cli

**Comment by botto** [comment]
My thought was to merge these as the CLI as a whole is working, so it's backwards compatible (but please do test if you have a chance, I might have missed something).
Then I'll move `sync`, `report` and `remove` over as well. Trying to avoid this become more of a monster PR

**Comment by botto** [comment]
Re `util` and `config`:

The `config` in the CLI is related to the json file handling, so this would only every be part of the CLI, if something else wants to also store it's config in json then maybe we could split it out in to it's own package.
Eventually the plan is to have the abstract store which the CLI could use and or other tools (i.e. `dsnet-gui`) could also use

The `util` is just for helpers to work with the CLI

**Review by naggie — APPROVED** [review]

**Pull request merged**
