### PR TITLE
Abstracted store

### PR DESCRIPTION
**Pull request by botto**
Started an inital idea for abstracted store.

I'm going to implement a sqlite interface as well to check that this works when we add more backends, but I don't think there be hidden dragons in this design.

wdyt @naggie

### CODE REVIEW

**Comment by botto** [comment]
Not sure what happend to the build here, I'm not able to replicate this locally so a little unsure what's happening.

**Comment by naggie** [comment]
Could you remove the vendor changes from this PR please? It's a bit impossible to review otherwise.

Maybe we should remove the vendor dir altogether, relying on go.mod etc.

**Comment by naggie** [comment]
@botto still want to do this? Or should we close it?

**Comment by botto** [comment]
I might try and refactor some of the bits out of this

**Pull request closed without merging**
